"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import type { ButtonHTMLAttributes } from "react";
import { CloseIcon } from "@/components/icons";
import { normalizeMermaidCode, validateMermaidCode } from "@/components/SkillDiagramPreview";
import { ModeToggleButton, WorkflowDiagramWorkspace } from "@/components/SkillWorkspace";

function PrimaryButton({
  children,
  className = "",
  ...props
}: ButtonHTMLAttributes<HTMLButtonElement>) {
  return (
    <button
      {...props}
      className={`inline-flex items-center justify-center rounded-lg border border-[#2f6fdd] bg-[#2f6fdd] px-4 py-2.5 text-sm font-semibold text-white transition-opacity hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50 ${className}`}
    >
      {children}
    </button>
  );
}

function SecondaryButton({
  children,
  className = "",
  ...props
}: ButtonHTMLAttributes<HTMLButtonElement>) {
  return (
    <button
      {...props}
      className={`inline-flex shrink-0 whitespace-nowrap items-center justify-center rounded-lg border border-[#cbd5e1] bg-white px-4 py-2 text-xs font-semibold text-[#334155] transition-colors hover:bg-[#f8fbff] disabled:cursor-not-allowed disabled:opacity-50 ${className}`}
    >
      {children}
    </button>
  );
}

export function buildFallbackWorkflow(skillMdContent: string): string {
  const phaseNames = Array.from(
    new Set(
      Array.from(
        skillMdContent.matchAll(/^##\s+(?:Phase|状态)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*$/gm),
      ).map((match) => match[1]),
    ),
  );
  const nodes = phaseNames.length > 0 ? phaseNames : ["draft"];
  const lines = ["```mermaid", "stateDiagram-v2", `  [*] --> ${nodes[0]}`];

  for (let i = 0; i < nodes.length - 1; i += 1) {
    lines.push(`  ${nodes[i]} --> ${nodes[i + 1]}`);
  }

  lines.push(`  ${nodes[nodes.length - 1]} --> [*]`);
  lines.push("```");
  return lines.join("\n");
}

export interface ValidationResult {
  ok: boolean;
  errors: string[];
  warnings: string[];
}

export type SubmitGateReason =
  | "basic_info"
  | "abilities"
  | "save_required"
  | "skill_md"
  | "diagram"
  | "ready";

export interface SubmitGateInput {
  basicInfoDone: boolean;
  abilitiesSelected: boolean;
  skillSaved: boolean;
  diagramDone: boolean;
  skillMdContent: string;
  validationResult?: ValidationResult | null;
}

export function getSubmitGateReason({
  basicInfoDone,
  abilitiesSelected,
  skillSaved,
  diagramDone,
  validationResult,
}: SubmitGateInput): SubmitGateReason {
  if (!basicInfoDone) return "basic_info";
  if (!abilitiesSelected) return "abilities";
  if (!skillSaved) return "save_required";
  if (validationResult && !validationResult.ok) return "skill_md";
  if (!diagramDone) return "diagram";
  return "ready";
}

interface Props {
  t: (key: string, values?: Record<string, string | number>) => string;
  skillSaved: boolean;
  skillMdContent: string;
  initialDiagramMermaid?: string;
  onDiagramSuccess?: () => void;
  onDiagramGenerated?: (mermaid: string) => void;
}

export default function SubmitSection({
  t,
  skillSaved,
  skillMdContent,
  initialDiagramMermaid,
  onDiagramSuccess,
  onDiagramGenerated,
}: Props) {
  const [diagramStatus, setDiagramStatus] = useState<"idle" | "loading" | "success" | "error">("idle");
  const [diagramMermaid, setDiagramMermaid] = useState("");
  const [diagramError, setDiagramError] = useState("");
  const [diagramValidationResult, setDiagramValidationResult] = useState<ValidationResult | null>(null);
  const [previewMode, setPreviewMode] = useState(true);
  const [editedCode, setEditedCode] = useState("");
  const autoGeneratedOnceRef = useRef(false);
  const lastInitialDiagramMermaidRef = useRef<string>("");
  const validationTimerRef = useRef<ReturnType<typeof setTimeout>>();

  useEffect(() => {
    const normalized = normalizeMermaidCode(initialDiagramMermaid ?? "");
    const initialDiagramChanged = normalized !== lastInitialDiagramMermaidRef.current;
    lastInitialDiagramMermaidRef.current = normalized;

    if (!normalized) {
      setDiagramStatus("idle");
      setDiagramMermaid("");
      setDiagramError("");
      setPreviewMode(true);
      setEditedCode("");
      setDiagramValidationResult(null);
      autoGeneratedOnceRef.current = false;
      return;
    }

    if (initialDiagramChanged || diagramMermaid.trim().length === 0) {
      setDiagramStatus("success");
      setDiagramMermaid(normalized);
      setEditedCode(normalized);
      setDiagramValidationResult(null);
      autoGeneratedOnceRef.current = true;
    }
  }, [diagramMermaid, initialDiagramMermaid]);

  const handleGenerateDiagram = useCallback(async () => {
    if (!skillMdContent.trim()) return;
    if (!skillSaved) {
      setDiagramStatus("error");
      setDiagramError(t("wizard_save_required"));
      return;
    }

    const hadDiagram = diagramMermaid.trim().length > 0;
    setDiagramStatus("loading");
    setDiagramError("");
    try {
      const res = await fetch("/api/skills/diagram", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ skillMdContent }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed");

      const generated = normalizeMermaidCode(data.mermaid || "");
      if (!generated) {
        throw new Error(t("diagram_empty_block"));
      }

      setDiagramMermaid(generated);
      setEditedCode(generated);
      setPreviewMode(true);
      onDiagramGenerated?.(generated);
      setDiagramStatus("success");
      onDiagramSuccess?.();
    } catch (err) {
      setDiagramError(err instanceof Error ? err.message : String(err));
      setDiagramStatus(hadDiagram ? "success" : "error");
    }
  }, [diagramMermaid, onDiagramGenerated, onDiagramSuccess, skillMdContent, skillSaved, t]);

  useEffect(() => {
    if (!skillSaved || autoGeneratedOnceRef.current || !skillMdContent.trim()) {
      return;
    }
    autoGeneratedOnceRef.current = true;
    void handleGenerateDiagram();
  }, [handleGenerateDiagram, skillMdContent, skillSaved]);

  const canGenerateDiagram = skillSaved && skillMdContent.trim().length > 0;
  const hasDiagram = diagramStatus === "success" && diagramMermaid.trim().length > 0;

  const openEditMode = useCallback(() => {
    setEditedCode(normalizeMermaidCode(diagramMermaid));
    setDiagramError("");
    setPreviewMode(false);
  }, [diagramMermaid]);

  const cancelEditMode = useCallback(() => {
    setEditedCode(normalizeMermaidCode(diagramMermaid));
    setDiagramError("");
    setPreviewMode(true);
  }, [diagramMermaid]);

  const saveEditMode = useCallback(async () => {
    const normalized = normalizeMermaidCode(editedCode);
    if (!normalized) {
      setDiagramValidationResult({
        ok: false,
        errors: [t("diagram_empty_block")],
        warnings: [],
      });
      setDiagramError("");
      return;
    }

    const validation = await validateMermaidCode(normalized);
    if (!validation.ok) {
      setDiagramValidationResult({
        ok: false,
        errors: [`Mermaid: ${t("diagram_syntax_error")}`],
        warnings: [],
      });
      setDiagramError("");
      return;
    }

    setDiagramMermaid(normalized);
    setEditedCode(normalized);
    setPreviewMode(true);
    setDiagramError("");
    setDiagramValidationResult(null);
    setDiagramStatus("success");
    onDiagramGenerated?.(normalized);
    onDiagramSuccess?.();
  }, [editedCode, onDiagramGenerated, onDiagramSuccess, t]);

  useEffect(() => {
    clearTimeout(validationTimerRef.current);

    if (previewMode || !editedCode.trim()) {
      if (!editedCode.trim()) {
        setDiagramValidationResult(null);
      }
      return;
    }

    validationTimerRef.current = setTimeout(() => {
      void (async () => {
        const normalized = normalizeMermaidCode(editedCode);
        if (!normalized) {
          setDiagramValidationResult(null);
          return;
        }

        const validation = await validateMermaidCode(normalized);
        if (!validation.ok) {
          setDiagramValidationResult({
            ok: false,
            errors: [`Mermaid: ${t("diagram_syntax_error")}`],
            warnings: [],
          });
          return;
        }

        setDiagramValidationResult({
          ok: true,
          errors: [],
          warnings: [],
        });
      })();
    }, 300);

    return () => clearTimeout(validationTimerRef.current);
  }, [editedCode, previewMode, t]);

  const actions = (
    <>
      {hasDiagram ? (
        <>
          <ModeToggleButton
            mode={previewMode ? "preview" : "edit"}
            onClick={previewMode ? openEditMode : cancelEditMode}
            editLabel={t("wizard_edit") ?? "编辑"}
            previewLabel={t("wizard_preview") ?? "预览"}
          />
          <button
            type="button"
            onClick={() => {
              void saveEditMode();
            }}
            className="shrink-0 whitespace-nowrap rounded-lg border border-[#2f6fdd] bg-[#2f6fdd] px-4 py-2 text-xs font-semibold text-white transition-opacity hover:opacity-90"
          >
            {t("wizard_save") ?? "保存"}
          </button>
          <SecondaryButton onClick={handleGenerateDiagram}>
            {t("wizard_regenerate_diagram")}
          </SecondaryButton>
        </>
      ) : (
        <PrimaryButton onClick={handleGenerateDiagram} disabled={!canGenerateDiagram}>
          {diagramStatus === "loading" ? t("diagram_loading") : t("wizard_generate_diagram")}
        </PrimaryButton>
      )}
    </>
  );

  const footer = (
    <div className="px-7 pb-6">
      {!previewMode && diagramValidationResult && (
        <div className="mb-3 flex items-center justify-between gap-3 rounded-lg border border-[#d8dde6] bg-[#f8fafc] px-4 py-2.5">
          <div className="flex min-w-0 items-center gap-2">
            <span
              className={`inline-flex h-2.5 w-2.5 shrink-0 rounded-full ${
                diagramValidationResult.ok
                  ? "bg-emerald-500"
                  : diagramValidationResult.errors.length > 0
                    ? "bg-red-500"
                    : "bg-amber-500"
              }`}
            />
            <p className="truncate text-xs font-semibold text-[#334155]">
              {diagramValidationResult.ok
                ? t("wizard_live_validation_passed")
                : diagramValidationResult.errors.length > 0
                  ? `${t("wizard_live_validation_errors_prefix")} ${diagramValidationResult.errors.length}`
                  : `${t("wizard_live_validation_warnings_prefix")} ${diagramValidationResult.warnings.length}`}
            </p>
          </div>
          <p className="shrink-0 text-[11px] text-[#64748b]">{t("wizard_live_validation_hint")}</p>
        </div>
      )}

      {!previewMode && diagramValidationResult && !diagramValidationResult.ok && (
        <div className="mb-3 rounded-lg border border-red-200 bg-red-50 px-4 py-2.5">
          <h4 className="mb-1 flex items-center gap-1.5 text-xs font-bold text-red-700">
            <CloseIcon className="h-3.5 w-3.5" />
            {t("wizard_validation_errors")}
          </h4>
          <ul className="space-y-0.5">
            {diagramValidationResult.errors.map((err, i) => (
              <li key={i} className="text-xs text-red-600">
                {err}
              </li>
            ))}
          </ul>
        </div>
      )}

      {!skillSaved && (
        <div className="mb-4 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3">
          <p className="text-sm text-amber-900">{t("wizard_save_required")}</p>
        </div>
      )}

      {diagramStatus === "loading" && (
        <div className="mb-4 flex items-center gap-3 rounded-lg border border-[#dbeafe] bg-[#eff6ff] px-4 py-3">
          <svg className="h-5 w-5 animate-spin text-[#1d4ed8]" viewBox="0 0 24 24" fill="none">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
          <span className="text-sm text-[#1e3a8a]">{t("diagram_loading")}</span>
        </div>
      )}

      {diagramError && (
        <div className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3">
          <p className="text-sm text-red-600">{diagramError}</p>
        </div>
      )}
    </div>
  );

  return (
    <WorkflowDiagramWorkspace
      title={`4. ${t("wizard_step4_title")}`}
      description={t("wizard_step4_desc")}
      descriptionClassName="max-w-[680px]"
      mermaid={previewMode ? diagramMermaid : editedCode}
      mode={previewMode ? "preview" : "edit"}
      onChange={setEditedCode}
      actions={actions}
      footer={footer}
      sourceTitle={t("diagram_source_title")}
      hideContent={!diagramMermaid.trim() && (diagramStatus === "loading" || !skillSaved)}
      collapsible
    />
  );
}
